import Editor, { loader, type Monaco } from "@monaco-editor/react";
import type { editor } from "monaco-editor";
import { useCallback, useEffect, useMemo, useState } from "react";
import { installShikiTheme, SHIKI_THEME } from "./shiki-monaco";

/**
 * Monaco is served from *our own* origin (`public/monaco/vs`, generated by
 * `bin/sync-monaco.js`) instead of `@monaco-editor/react`'s default jsDelivr
 * CDN: this app runs on a LAN and may have no internet access, in which case
 * a CDN fetch would leave the viewer spinning forever.
 *
 * `loader.config` has to run before the first `<Editor>` mounts, and this
 * module is only ever imported in the browser (see `code-editor.tsx`), so
 * module scope is the right place for it.
 */
loader.config({ paths: { vs: "/monaco/vs" } });

/**
 * Turns an absolute filesystem path into a model URI.
 *
 * The path is produced server-side and is native, so on Windows it arrives
 * with backslashes and a drive letter. Monaco only uses this as a model
 * identity + a hint for the TS worker, so all that matters is that it is
 * unique per file and keeps the extension.
 */
function toModelPath(filePath: string): string {
  const normalized = filePath.replace(/\\/g, "/");
  return normalized.startsWith("/") ? normalized : `/${normalized}`;
}

type Props = {
  /** Absolute path of the file; identifies the model. */
  filePath: string;
  language: string;
  value: string;
  loading?: React.ReactNode;
};

/**
 * Read-only Monaco instance used by the file preview.
 *
 * Client-only: importing this module pulls in `@monaco-editor/react`, which
 * expects a DOM. Always reach it through `code-editor.tsx`.
 */
export default function CodeEditorClient({
  filePath,
  language,
  value,
  loading,
}: Props) {
  const modelPath = useMemo(() => toModelPath(filePath), [filePath]);

  // the editor is not created until the theme + this file's grammar are in
  // place: `shikiToMonaco` patches `monaco.editor.create` to apply the theme,
  // so an editor created first would render with monaco's default palette
  const [isThemeReady, setIsThemeReady] = useState(false);

  useEffect(() => {
    let isActive = true;

    // `loader.init()` resolves with the same monaco instance `<Editor>` uses,
    // loading it from `/monaco/vs` if it isn't already there
    loader
      .init()
      .then((monaco) => installShikiTheme(monaco, language))
      .then(() => {
        if (isActive) setIsThemeReady(true);
      });

    return () => {
      isActive = false;
    };
    // re-runs when the open file's language changes, to pull in that grammar.
    // `isThemeReady` is never reset: unmounting the editor mid-session would
    // throw away scroll state to swap a tokenizer that can be swapped in place
  }, [language]);

  const options = useMemo<editor.IStandaloneEditorConstructionOptions>(
    () => ({
      readOnly: true,
      // without this the hidden textarea still accepts input and the
      // "cannot edit in read-only editor" toast fires on every keystroke
      domReadOnly: true,
      minimap: { enabled: false },
      lineNumbers: "on",
      wordWrap: "on",
      // the panel is resizable, so the editor has to re-measure itself
      automaticLayout: true,
      scrollBeyondLastLine: false,
      renderLineHighlight: "none",
      occurrencesHighlight: "off",
      selectionHighlight: false,
      fontSize: 12,
      fontFamily:
        "'JetBrains Mono Variable', ui-monospace, SFMono-Regular, monospace",
      scrollbar: { alwaysConsumeMouseWheel: false },
      padding: { top: 8, bottom: 8 },
      stickyScroll: { enabled: false },
    }),
    [],
  );

  const handleBeforeMount = useCallback((monaco: Monaco) => {
    // IntelliSense: hovers, signature help, JSON schema validation.
    //
    // Semantic diagnostics are off on purpose. The preview opens one file at a
    // time with no tsconfig and no sibling modules loaded, so every import
    // would be flagged "cannot find module" -- errors about the *viewer*, not
    // about the code. Syntax errors are real, so those stay on.
    for (const defaults of [
      monaco.languages.typescript.typescriptDefaults,
      monaco.languages.typescript.javascriptDefaults,
    ]) {
      defaults.setDiagnosticsOptions({
        noSemanticValidation: true,
        noSyntaxValidation: false,
      });
      defaults.setCompilerOptions({
        target: monaco.languages.typescript.ScriptTarget.ESNext,
        module: monaco.languages.typescript.ModuleKind.ESNext,
        moduleResolution:
          monaco.languages.typescript.ModuleResolutionKind.NodeJs,
        jsx: monaco.languages.typescript.JsxEmit.ReactJSX,
        allowJs: true,
        allowNonTsExtensions: true,
        esModuleInterop: true,
      });
    }

    monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
      validate: true,
      allowComments: true,
      // no network in this deployment, so remote `$schema` refs would hang
      enableSchemaRequest: false,
      schemas: [],
    });
  }, []);

  if (!isThemeReady) return loading ?? null;

  return (
    <Editor
      theme={SHIKI_THEME}
      height="100%"
      // `path` gives each file its own model, so switching files keeps view
      // state (scroll, folds) instead of rewriting one shared buffer
      path={modelPath}
      language={language}
      value={value}
      options={options}
      beforeMount={handleBeforeMount}
      loading={loading ?? null}
    />
  );
}
